version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build: ./user-service
    depends_on:
      - eureka-server
      - user-db
    ports:
      - "8081:8081"
    networks:
      - backend

  company-service:
    build: ./company-service
    depends_on:
      - eureka-server
      - company-db
    ports:
      - "8082:8082"
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    depends_on:
      - eureka-server
      - user-service
      - company-service
    ports:
      - "8080:8080"
    networks:
      - backend

  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  company-db:
    image: postgres
    container_name: company-db
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - backend

networks:
  backend:
